# https://kubernetes.io/docs/tutorials/k8s101/
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
      readOnly: false
  volumes:
  - name: redis-storage
    emptyDir: {}
